patreon: # Replace with a single Patreon page
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
custom: https://www.buymeacoffee.com/nikoidot
